networks:
  laravel:
    name: laravel
services:
  nginx:
    # image: nginx:latest
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  # apache:
  #   build:
  #     context: .
  #     dockerfile: apache.dockerfile
  #   container_name: apache
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./src:/var/www/html
  #   networks:
  #     - laravel
  php:
    # image: php:8.2-fpm-alpine
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 4306:3306
    # env_file:
    #   - ./env/mysql.env
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - laravel
  queue-worker:
    extends:
      service: artisan
    container_name: queue-worker
    command: queue:work
    restart: always
  scheduler:
    extends:
      service: artisan
    container_name: scheduler
    command: schedule:work
    restart: always
  phpunit:
    extends:
      service: artisan
    container_name: phpunit
    command: test
  reverb:
    extends:
      service: artisan
    container_name: reverb
    command: reverb:start
    restart: always
  npm:
    image: node:current-alpine
    container_name: npm
    working_dir: /var/www/html
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - laravel
