networks:
  laravel:
    name: laravel
services:
  php:
    image: php:8.2-fpm-alpine
    container_name: php
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    # environment:
    #   MYSQL_DATABASE: laraveldb
    #   MYSQL_USER: laravel
    #   MYSQL_PASSWORD: secret
    #   MYSQL_ROOT_PASSWORD: secret
    env_file:
      - ./env/mysql.env
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - laravel
